import flet as fl

BACKGROUND = fl.Colors.SURFACE
SURFACE = fl.Colors.SURFACE_CONTAINER_LOW
GREEN = fl.Colors.PRIMARY
TEXT = fl.Colors.ON_SURFACE
MUTED = fl.Colors.ON_SURFACE_VARIANT
BORDER = fl.Colors.OUTLINE_VARIANT
ERROR = fl.Colors.ERROR

SIDEBAR = '#153638'
SIDEBAR_HOVER = '#25494B'
ACCENT = '#D4F59B'
MESSAGE_BACKGROUND = '#245B4D'
